name: test workflow
on: push
jobs:
   npmjobs: 
    runs-on: ubuntu-latest
    steps:
      - name: Getcode
        uses: actions/checkout@v3
      - name: Run depemdencies
        run: npm ci
      - name: Run Lint
        run: npm run lint
      - name: Run test
        run: npm run test
      - name: Run build
        run: npm run build

